# Name of the workflow
name: GitHub Action Environment Secrets & Variables
# Name of the workflow instance
run-name: Test using GitHub Secrets & Variables

# Specify how the workflow is triggered
# In this scenario, the workflow is manually dispatched.
# And users can specify an input text message
on:
  workflow_dispatch:
    inputs:
      my_env: # Dev or Staging or Prod
        default: "Dev"
        description: 'Specify environment'

env:
  env_var1: 'Workflow Environment Variable 1'
  env_var2: 'Workflow Environment Variable 2'

# Specify a list of jobs to run
jobs:

  job_1: # name of job 2
    environment: ${{ github.event.inputs.my_env }}
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ env.env_var1 }}'
      - run: echo '${{ env.env_var2 }}'
      - run: echo '${{ github.event.inputs.my_env }}'
      - run: echo '${{ vars.HOST }}'
      - run: echo '${{ secrets.PASSWORD }}'
